/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IsbnRouteImport } from './routes/$isbn'
import { Route as IndexRouteImport } from './routes/index'

const IsbnRoute = IsbnRouteImport.update({
  id: '/$isbn',
  path: '/$isbn',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$isbn': typeof IsbnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$isbn': typeof IsbnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$isbn': typeof IsbnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$isbn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$isbn'
  id: '__root__' | '/' | '/$isbn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IsbnRoute: typeof IsbnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$isbn': {
      id: '/$isbn'
      path: '/$isbn'
      fullPath: '/$isbn'
      preLoaderRoute: typeof IsbnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IsbnRoute: IsbnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
